TRANSLATIONS = {
    "pt": {
        "nav_home": "Início",
        "nav_about": "Sobre",
        "nav_trajectory": "Trajetória",
        "nav_projects": "Projetos",
        "nav_contact": "Contato",
        "role_backend": "Back-End",
        "role_data": "Dados",
        "hero_badge": "Data & Backend Developer",
        "home_title_prefix": "Olá, sou o",
        "home_title_name": "João Lucas",
        "home_subtitle_main": "Desenvolvedor focado em transformar dados e código em soluções de alto impacto. Com sólida experiência em Python, SQL, APIs e Inteligência de Dados.",
        "metric_exp": "Anos de <br> Experiência",
        "metric_proj": "Projetos <br> Concluídos",
        "metric_cert": "Certificações <br> Técnicas",
        "home_btn_projects": "Ver Projetos",
        "home_btn_cv": "Baixar CV",
        "about_title": "Sobre Mim",
        "about_bio_items": "Sou um profissional apaixonado por tecnologia e inovação, focado em transformar problemas complexos em soluções escaláveis. Busco constantemente aprimorar minhas habilidades em arquitetura de software e gerar impacto positivo através de código limpo e eficiente.",
        "about_bio_data": "Com uma base sólida em infraestrutura e suporte técnico, direcionei minha carreira para a <strong>Análise de Dados</strong>. Minha paixão é utilizar a tecnologia para resolver problemas de negócio. <br><br> Hoje, utilizo <strong>Python, SQL e Power BI</strong> para automatizar processos de ETL, modelar bancos de dados e criar dashboards que eliminam o 'achismo' e trazem certeza para a tomada de decisão.",
        "skill_db": "Banco de Dados",
        "skill_formation": "Formação",
        "skill_formation_sys": "Análise e Desenvolvimento de Sistemas",
        "skill_formation_cs": "Ciência da Computação",
        "skill_location": "Localização",
        "trajectory_title": "Experiência Profissional",
        "trajectory_subtitle": "Minha Jornada",
        "traj_role_curr": "Assistente Financeiro – Contas a Receber",
        "traj_company_curr": "Associação Beneficente Síria - HCOR",
        "traj_date_curr": "jan/2025 – atualmente",
        "traj_badge_curr": "Atual",
        "traj_desc_curr": "• Implemento dashboards em <strong>Power BI</strong> para monitorar recebimentos. <br> • Desenvolvo relatórios em <strong>SQL</strong> para análise de créditos não identificados. <br> • Crio ferramenta em <strong>Python</strong> para envio automatizado de cobranças. <br> • Realizo conciliação bancária e controle de créditos.",
        
        "traj_role_prev1": "Assistente Financeiro – Crédito e Cobrança",
        "traj_company_prev1": "Hospital Alemão Oswaldo Cruz",
        "traj_date_prev1": "jan/2024 – dez/2024",
        "traj_desc_prev1": "• Desenvolvi relatórios de inadimplência com <strong>SQL</strong>, apoiando decisões de gestão. <br> • Apresentei resultados financeiros com <strong>PowerPoint e Excel</strong>. <br> • Automatizei processos de cobrança por meio de querys em <strong>SQL</strong>.",
        
        "traj_role_prev2": "Auxiliar Administrativo – Crédito e Cobrança",
        "traj_company_prev2": "Associação Beneficente Síria - HCOR",
        "traj_date_prev2": "abr/2023 – jan/2024",
        "traj_desc_prev2": "• Analisei créditos não identificados e consolidei relatórios para regularização de saldos. <br> • Realizei envios massivos de cobranças e acompanhei os retornos.",
        "projects_title_backend": "Meus Projetos Back-End",
        "projects_subtitle_backend": "O que tenho construído",
        "projects_title_data": "Projetos de Dados",
        "projects_subtitle_data": "Visualizações e Análises",
        "proj_ecommerce_desc": "API RESTful completa com autenticação JWT, integração com pagamentos e gestão de estoque.",
        "proj_notify_desc": "Sistema escalável de envio de e-mails e push notifications usando filas (RabbitMQ).",
        "proj_sales_desc": "Dashboard interativo no Power BI para monitoramento de KPIs de vendas mensais.",
        "proj_etl_desc": "Script Python automatizado para limpeza e carga de dados de diversas fontes.",
        "btn_demo": "Demo",
        "btn_dashboard": "Ver Dashboard",
        "contact_title": "Fale comigo",
        "contact_subtitle": "Entre em contato",
        "contact_email_btn": "Escrever",
        "contact_wa_btn": "Mensagem",
        "contact_li_btn": "Conectar",
        "footer_rights": "&#169; João. Todos os direitos reservados."
    },
    "en": {
        "nav_home": "Home",
        "nav_about": "About",
        "nav_trajectory": "Trajectory",
        "nav_projects": "Projects",
        "nav_contact": "Contact",
        "role_backend": "Back-End",
        "role_data": "Data",
        "hero_badge": "Data & Backend Developer",
        "home_title_prefix": "Hello, I'm",
        "home_title_name": "João Lucas",
        "home_subtitle_main": "Developer focused on transforming data and code into high-impact solutions. With solid experience in Python, SQL, APIs and Data Intelligence.",
        "metric_exp": "Years of <br> Experience",
        "metric_proj": "Projects <br> Completed",
        "metric_cert": "Technical <br> Certifications",
        "home_btn_projects": "View Projects",
        "home_btn_cv": "Download CV",
        "about_title": "About Me",
        "about_bio_items": "I am a professional passionate about technology and innovation, focused on transforming complex problems into scalable solutions. I constantly seek to improve my skills in software architecture and generate positive impact through clean and efficient code.",
        "about_bio_data": "With a solid foundation in infrastructure and technical support, I directed my career towards <strong>Data Analysis</strong>. My passion is using technology to solve business problems. <br><br> Today, I use <strong>Python, SQL, and Power BI</strong> to automate ETL processes, model databases, and create dashboards that eliminate guesswork and bring certainty to decision-making.",
        "skill_db": "Databases",
        "skill_formation": "Education",
        "skill_formation_sys": "Analysis and Systems Development",
        "skill_formation_cs": "Computer Science",
        "skill_location": "Location",
        "trajectory_title": "Professional Experience",
        "trajectory_subtitle": "My Journey",
        "traj_role_curr": "Financial Assistant – Accounts Receivable",
        "traj_company_curr": "Associação Beneficente Síria - HCOR",
        "traj_date_curr": "Jan/2025 – Present",
        "traj_badge_curr": "Current",
        "traj_desc_curr": "• Implement <strong>Power BI</strong> dashboards to monitor receipts. <br> • Develop <strong>SQL</strong> reports for analysis of unidentified credits. <br> • Create <strong>Python</strong> tools for automated billing. <br> • Perform bank reconciliation and credit control.",
        
        "traj_role_prev1": "Financial Assistant – Credit and Collections",
        "traj_company_prev1": "Hospital Alemão Oswaldo Cruz",
        "traj_date_prev1": "Jan/2024 – Dec/2024",
        "traj_desc_prev1": "• Developed delinquency reports with <strong>SQL</strong>, supporting management decisions. <br> • Presented financial results with <strong>PowerPoint and Excel</strong>. <br> • Automated collection processes through <strong>SQL</strong> queries.",
        
        "traj_role_prev2": "Administrative Assistant – Credit and Collections",
        "traj_company_prev2": "Associação Beneficente Síria - HCOR",
        "traj_date_prev2": "Apr/2023 – Jan/2024",
        "traj_desc_prev2": "• Analyzed unidentified credits and consolidated reports for balance regularization. <br> • Performed massive collection mailings and monitored returns.",
        "projects_title_backend": "My Back-End Projects",
        "projects_subtitle_backend": "What I've been building",
        "projects_title_data": "Data Projects",
        "projects_subtitle_data": "Visualizations and Analytics",
        "proj_ecommerce_desc": "Complete RESTful API with JWT authentication, payment integration, and inventory management.",
        "proj_notify_desc": "Scalable email and push notification system using queues (RabbitMQ).",
        "proj_sales_desc": "Interactive Power BI dashboard for monitoring monthly sales KPIs.",
        "proj_etl_desc": "Automated Python script for cleaning and loading data from various sources.",
        "btn_demo": "Demo",
        "btn_dashboard": "View Dashboard",
        "contact_title": "Talk to me",
        "contact_subtitle": "Get in touch",
        "contact_email_btn": "Write me",
        "contact_wa_btn": "Message",
        "contact_li_btn": "Connect",
        "footer_rights": "&#169; João. All rights reserved."
    }
}
